<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="My suite" duration-ms="23381" started-at="2019-09-09T17:07:08Z" finished-at="2019-09-09T17:07:32Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="23381" started-at="2019-09-09T17:07:08Z" finished-at="2019-09-09T17:07:32Z">
      <class name="com.tests.SwagLabsTests">
        <test-method status="PASS" signature="launchApp()[pri:0, instance:com.tests.SwagLabsTests@c038203]" name="launchApp" duration-ms="10034" started-at="2019-09-09T17:07:08Z" description="Launch and Login" finished-at="2019-09-09T17:07:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method status="PASS" signature="sort()[pri:0, instance:com.tests.SwagLabsTests@c038203]" name="sort" duration-ms="10004" started-at="2019-09-09T17:07:21Z" description="Sort the Products" depends-on-methods="com.tests.SwagLabsTests.launchApp" finished-at="2019-09-09T17:07:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sort -->
        <test-method status="FAIL" signature="selectAProduct()[pri:0, instance:com.tests.SwagLabsTests@c038203]" name="selectAProduct" duration-ms="10" started-at="2019-09-09T17:07:31Z" description="Select a Product" depends-on-methods="com.tests.SwagLabsTests.sort" finished-at="2019-09-09T17:07:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sauce Lbs Backpack] but found [Sauce Labs Backpack]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sauce Lbs Backpack] but found [Sauce Labs Backpack]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.tests.SwagLabsTests.selectAProduct(SwagLabsTests.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectAProduct -->
        <test-method status="SKIP" signature="goToAboutPage()[pri:0, instance:com.tests.SwagLabsTests@c038203]" name="goToAboutPage" duration-ms="0" started-at="2019-09-09T17:07:31Z" description="Go to About Page" depends-on-methods="com.tests.SwagLabsTests.selectAProduct" finished-at="2019-09-09T17:07:31Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SwagLabsTests.goToAboutPage()[pri:0, instance:com.tests.SwagLabsTests@c038203] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SwagLabsTests.goToAboutPage()[pri:0, instance:com.tests.SwagLabsTests@c038203] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToAboutPage -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:com.tests.SwagLabsTests@c038203]" name="logout" duration-ms="0" started-at="2019-09-09T17:07:31Z" description="Logout" depends-on-methods="com.tests.SwagLabsTests.goToAboutPage" finished-at="2019-09-09T17:07:31Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SwagLabsTests.logout()[pri:0, instance:com.tests.SwagLabsTests@c038203] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SwagLabsTests.logout()[pri:0, instance:com.tests.SwagLabsTests@c038203] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.tests.SwagLabsTests -->
    </test> <!-- Test1 -->
  </suite> <!-- My suite -->
</testng-results>
